# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import pastes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to=pastes.models.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='TextUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_cache', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=64, null=True)),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
